package demo

title :: "Sokoban Demo!"
TILE_SIZE :: 64
ROWS :: 10
COLS :: 20
screen_width :: 1280
screen_height :: 720
CAMERA_VIEW_TILES_X :: 3
CAMERA_VIEW_TILES_Y :: 3
CAMERA_VIEW_WIDTH :: CAMERA_VIEW_TILES_X * TILE_SIZE
CAMERA_VIEW_HEIGHT :: CAMERA_VIEW_TILES_Y * TILE_SIZE